[project]
name = "lan-pipeline-minimal"
version = "0.1.0"
description = "Environment to create and submit sbatch scripts to run ssm-simulators or LANfactory on Oscar"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
]
